global:
  node_name: "yrlab1"
  datastore_id: "local-lvm"

configs:
  talos-cp-01:
    enabled: true
    role: "controlplane"
    bootstrap: true
    node_name: "yrlab1"
  talos-worker-01:
    enabled: true
    role: "worker"
    node_name: "yrlab1"
