tags:
  - terraform

global:
  node_name: "yrlab1"
  datastore_id: "local-lvm"
  cores: 2
  ram: 2048
  disk_size: 200
  pool_id: "k8s"
  boot_order: ["sata0"]
  startup_order: 2
  startup_up_delay: 5
  cpu_type: "host"
  network_bridge: "vmbr0"
  os_type: "l26"
  description: "Talos Linux VM for Kubernetes cluster"

vms:
  talos-cp-01:
    node_name: "yrlab1"
    enabled: true
    vm_id: 111
    tags: ["controlplane", "talos", "kubernetes"]
    image_file: talos-nocloud
    cores: 2
    ram: 8192
    disk_size: 200
  talos-worker-01:
    node_name: "yrlab1"
    enabled: true
    vm_id: 112
    tags: ["worker", "talos", "kubernetes"]
    image_file: talos-nocloud
    cores: 2
    ram: 8192
    disk_size: 200
